### ISSUE TITLE
composer create-project -sdev laminas/laminas-mvc-skeleton broken - Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given

### ISSUE THREAD

**Issue by flipkickmedia** [laminas/laminas-mvc-skeleton#24]
php7.3 on ubuntu20

Seems Laminas is broken out of the box with instructions from the getting started guide at https://docs.laminas.dev/laminas-mvc/quick-start/
```
$ composer create-project -sdev laminas/laminas-mvc-skeleton public/
Creating a "laminas/laminas-mvc-skeleton" project at "./public"
Installing laminas/laminas-mvc-skeleton (dev-master df7ec944ce1a041b155ed64ddbf31431225e2a04)
  - Installing laminas/laminas-mvc-skeleton (dev-master df7ec94): Cloning df7ec944ce from cache
Created project in /var/www/html/public/
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing laminas/laminas-zendframework-bridge (1.0.4): Loading from cache
  - Installing laminas/laminas-component-installer (2.2.0): Loading from cache
  - Installing laminas/laminas-skeleton-installer (0.1.7): Loading from cache
  - Installing laminas/laminas-stdlib (3.2.1): Loading from cache
  - Installing laminas/laminas-loader (2.6.1): Loading from cache
  - Installing laminas/laminas-eventmanager (3.2.1): Loading from cache
  - Installing laminas/laminas-json (3.1.2): Loading from cache
  - Installing laminas/laminas-view (2.11.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing laminas/laminas-servicemanager (3.4.1): Loading from cache
  - Installing laminas/laminas-validator (2.13.4): Loading from cache
  - Installing laminas/laminas-escaper (2.6.1): Loading from cache
  - Installing laminas/laminas-uri (2.7.1): Loading from cache
  - Installing laminas/laminas-http (2.12.0): Loading from cache
  - Installing laminas/laminas-router (3.3.2): Loading from cache
  - Installing laminas/laminas-config (3.3.0): Loading from cache
  - Installing laminas/laminas-modulemanager (2.8.4): Loading from cache
  - Installing laminas/laminas-mvc (3.1.1): Loading from cache
  - Installing laminas/laminas-development-mode (3.2.1): Loading from cache
laminas/laminas-json suggests installing laminas/laminas-json-server (For implementing JSON-RPC servers)
laminas/laminas-json suggests installing laminas/laminas-xml2json (For converting XML documents to JSON)
laminas/laminas-view suggests installing laminas/laminas-authentication (Laminas\Authentication component)
laminas/laminas-view suggests installing laminas/laminas-feed (Laminas\Feed component)
laminas/laminas-view suggests installing laminas/laminas-filter (Laminas\Filter component)
laminas/laminas-view suggests installing laminas/laminas-i18n (Laminas\I18n component)
laminas/laminas-view suggests installing laminas/laminas-mvc-plugin-flashmessenger (laminas-mvc-plugin-flashmessenger component, if you want to use the FlashMessenger view helper with laminas-mvc versions 3 and up)
laminas/laminas-view suggests installing laminas/laminas-navigation (Laminas\Navigation component)
laminas/laminas-view suggests installing laminas/laminas-paginator (Laminas\Paginator component)
laminas/laminas-view suggests installing laminas/laminas-permissions-acl (Laminas\Permissions\Acl component)
laminas/laminas-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 1.* to handle lazy initialization of services)
laminas/laminas-validator suggests installing laminas/laminas-db (Laminas\Db component, required by the (No)RecordExists validator)
laminas/laminas-validator suggests installing laminas/laminas-filter (Laminas\Filter component, required by the Digits validator)
laminas/laminas-validator suggests installing laminas/laminas-i18n (Laminas\I18n component to allow translation of validation error messages)
laminas/laminas-validator suggests installing laminas/laminas-i18n-resources (Translations of validator messages)
laminas/laminas-validator suggests installing laminas/laminas-math (Laminas\Math component, required by the Csrf validator)
laminas/laminas-validator suggests installing laminas/laminas-session (Laminas\Session component, ^2.8; required by the Csrf validator)
laminas/laminas-validator suggests installing psr/http-message (psr/http-message, required when validating PSR-7 UploadedFileInterface instances via the Upload and UploadFile validators)
laminas/laminas-http suggests installing paragonie/certainty (For automated management of cacert.pem)
laminas/laminas-router suggests installing laminas/laminas-i18n (^2.7.4, if defining translatable HTTP path segments)
laminas/laminas-config suggests installing laminas/laminas-filter (^2.7.2; install if you want to use the Filter processor)
laminas/laminas-config suggests installing laminas/laminas-i18n (^2.7.4; install if you want to use the Translator processor)
laminas/laminas-modulemanager suggests installing laminas/laminas-console (Laminas\Console component)
laminas/laminas-mvc suggests installing http-interop/http-middleware (^0.4.1 to be used together with laminas-stratigility)
laminas/laminas-mvc suggests installing laminas/laminas-log (^2.9.1  To provide log functionality via LogFilterManager, LogFormatterManager, and LogProcessorManager)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-console (laminas-mvc-console provides the ability to expose laminas-mvc as a console application)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-i18n (laminas-mvc-i18n provides integration with laminas-i18n, including a translation bridge and translatable route segments)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-fileprg (To provide Post/Redirect/Get functionality around forms that container file uploads)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-flashmessenger (To provide flash messaging capabilities between requests)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-identity (To access the authenticated identity (per laminas-authentication) in controllers)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-prg (To provide Post/Redirect/Get functionality within controllers)
laminas/laminas-mvc suggests installing laminas/laminas-paginator (^2.7 To provide pagination functionality via PaginatorPluginManager)
laminas/laminas-mvc suggests installing laminas/laminas-psr7bridge ((^0.2) To consume PSR-7 middleware within the MVC workflow)
laminas/laminas-mvc suggests installing laminas/laminas-servicemanager-di (laminas-servicemanager-di provides utilities for integrating laminas-di and laminas-servicemanager in your laminas-mvc application)
laminas/laminas-mvc suggests installing laminas/laminas-stratigility (laminas-stratigility is required to use middleware pipes in the MiddlewareListener)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Writing lock file
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /usr/share/php/Composer/IO/ConsoleIO.php on line 263 and defined in /usr/share/php/Symfony/Component/Console/Question/Question.php:37
Stack trace:
#0 /usr/share/php/Composer/IO/ConsoleIO.php(263): Symfony\Component\Console\Question\Question->__construct(Array, 'y')
laminas/laminas-mvc#1 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(149): Composer\IO\ConsoleIO->ask(Array, 'y')
laminas/laminas-mvc#2 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(81): Laminas\SkeletonInstaller\OptionalPackagesInstaller->requestMinimalInstall()
laminas/laminas-mvc#3 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/Plugin.php(80): Laminas\SkeletonInstaller\Opt in /usr/share/php/Symfony/Component/Console/Question/Question.php on line 37

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /usr/share/php/Composer/IO/ConsoleIO.php on line 263 and defined in /usr/share/php/Symfony/Component/Console/Question/Question.php:37
Stack trace:
#0 /usr/share/php/Composer/IO/ConsoleIO.php(263): Symfony\Component\Console\Question\Question->__construct(Array, 'y')
laminas/laminas-mvc#1 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(149): Composer\IO\ConsoleIO->ask(Array, 'y')
laminas/laminas-mvc#2 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(81): Laminas\SkeletonInstaller\OptionalPackagesInstaller->requestMinimalInstall()
laminas/laminas-mvc#3 /var/www/html/public/vendor/laminas/laminas-skeleton-installer/src/Plugin.php(80): Laminas\SkeletonInstaller\Opt in /usr/share/php/Symfony/Component/Console/Question/Question.php on line 37
```

**Comment by samsonasik** [comment]
I transfered the issue to `laminas-mvc-skeleton`

**Comment by samsonasik** [comment]
What composer version you're using? I tried with php 7.4 and composer v1 stable and it is working fine. 

```
➜  ~ composer -V      
Composer version 1.10.10 2020-08-03 11:35:19

➜  ~ php -v
PHP 7.4.2 (cli) (built: Feb 17 2020 12:56:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans

➜  ~  composer create-project -sdev laminas/laminas-mvc-skeleton public/
    1/9:	http://repo.packagist.org/p/provider-2020-07$461a0f63477aa2c13c2e0cc6d28aee3ae2e9c407530be353e523fa135851948f.json
    2/9:	http://repo.packagist.org/p/provider-2019-10$ccadc72631710d6d20939d10da2c14472d06de4efd8a800083a29c7d50ec375b.json
    3/9:	http://repo.packagist.org/p/provider-latest$d648b8a46821a547c2d6d2cb21817d825ca6779eeaa7250cdafa775562baa6d1.json
    4/9:	http://repo.packagist.org/p/provider-2020-01$ac35cf7aea50b609a37201c84b6c3c2b4059caa2ecc505e45f3fd2f50fbe3e92.json
    5/9:	http://repo.packagist.org/p/provider-2016$1a2a06b2b4a8c04de962f33825c1e55a8dec8c91d2cfcf0035474c58e15d25ab.json
    6/9:	http://repo.packagist.org/p/provider-2017$70d8dbd513668a41ede252883e97efd41f7790f1ac9531a32e5bcea9b5a6a760.json
    7/9:	http://repo.packagist.org/p/provider-2020-04$d6d5803de978b434c46f0758cf857457e90751ce607d558e6c84e709b775a323.json
    8/9:	http://repo.packagist.org/p/provider-2019$7c3f864630b17713e21a3897374745f3300e4176884bf9fc9acb816bc16c1466.json
    9/9:	http://repo.packagist.org/p/provider-2018$cc56850349a087955e79080ef85dbd062bc64b0a94829442a056d7c9e58b55a0.json
    Finished: success: 9, skipped: 0, failure: 0, total: 9
    1/9:	http://repo.packagist.org/p/provider-2019-10$ccadc72631710d6d20939d10da2c14472d06de4efd8a800083a29c7d50ec375b.json
    2/9:	http://repo.packagist.org/p/provider-latest$d648b8a46821a547c2d6d2cb21817d825ca6779eeaa7250cdafa775562baa6d1.json
    3/9:	http://repo.packagist.org/p/provider-2020-07$461a0f63477aa2c13c2e0cc6d28aee3ae2e9c407530be353e523fa135851948f.json
    4/9:	http://repo.packagist.org/p/provider-2016$1a2a06b2b4a8c04de962f33825c1e55a8dec8c91d2cfcf0035474c58e15d25ab.json
    5/9:	http://repo.packagist.org/p/provider-2020-01$ac35cf7aea50b609a37201c84b6c3c2b4059caa2ecc505e45f3fd2f50fbe3e92.json
    6/9:	http://repo.packagist.org/p/provider-2020-04$d6d5803de978b434c46f0758cf857457e90751ce607d558e6c84e709b775a323.json
    7/9:	http://repo.packagist.org/p/provider-2019$7c3f864630b17713e21a3897374745f3300e4176884bf9fc9acb816bc16c1466.json
    8/9:	http://repo.packagist.org/p/provider-2017$70d8dbd513668a41ede252883e97efd41f7790f1ac9531a32e5bcea9b5a6a760.json
    9/9:	http://repo.packagist.org/p/provider-2018$cc56850349a087955e79080ef85dbd062bc64b0a94829442a056d7c9e58b55a0.json
    Finished: success: 9, skipped: 0, failure: 0, total: 9
Creating a "laminas/laminas-mvc-skeleton" project at "./public"
Installing laminas/laminas-mvc-skeleton (dev-master df7ec944ce1a041b155ed64ddbf31431225e2a04)
  - Installing laminas/laminas-mvc-skeleton (dev-master df7ec94): Cloning df7ec944ce from cache
Created project in /Users/samsonasik/www/public/
    1/2:	http://repo.packagist.org/p/provider-latest$2da48cce769def028f491172d909c5f0d8b12ff3898c86f67af366dfe7d5f325.json
    2/2:	http://repo.packagist.org/p/provider-2020-07$68185694c3252bccf8bd6f07b52254807b5392844f3f4e55cc314c9c020a1397.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/15:	https://codeload.github.com/php-fig/container/legacy.zip/b7ce3b176482dbbc1245ebf52b181af44c2cf55f
    2/15:	https://codeload.github.com/laminas/laminas-escaper/legacy.zip/25f2a053eadfa92ddacb609dcbbc39362610da70
    3/15:	https://codeload.github.com/laminas/laminas-modulemanager/legacy.zip/92b1cde1aab5aef687b863face6dd5d9c6751c78
    4/15:	https://codeload.github.com/laminas/laminas-config/legacy.zip/b8fe057f55e69a0e7a2e4ced79218a43f58606a8
    5/15:	https://codeload.github.com/container-interop/container-interop/legacy.zip/79cbf1341c22ec75643d841642dd5d6acd83bdb8
    6/15:	https://codeload.github.com/laminas/laminas-router/legacy.zip/01a6905202ad41a42ba63d60260eba32b89e18c7
    7/15:	https://codeload.github.com/laminas/laminas-mvc/legacy.zip/ead09f8ab5ff0e562dbd0198c7f67523c2f61980
    8/15:	https://codeload.github.com/laminas/laminas-view/legacy.zip/3bbb2e94287383604c898284a18d2d06cf17301e
    9/15:	https://codeload.github.com/laminas/laminas-json/legacy.zip/00dc0da7b5e5018904c5c4a8e80a5faa16c2c1c6
    10/15:	https://codeload.github.com/laminas/laminas-eventmanager/legacy.zip/ce4dc0bdf3b14b7f9815775af9dfee80a63b4748
    11/15:	https://codeload.github.com/laminas/laminas-loader/legacy.zip/5d01c2c237ae9e68bec262f339947e2ea18979bc
    12/15:	https://codeload.github.com/laminas/laminas-stdlib/legacy.zip/2b18347625a2f06a1a485acfbc870f699dbe51c6
    13/15:	https://codeload.github.com/laminas/laminas-skeleton-installer/legacy.zip/3cde5af4ded6b5d72deaa7388b8dcff0decc77d3
    14/15:	https://codeload.github.com/laminas/laminas-uri/legacy.zip/6be8ce19622f359b048ce4faebf1aa1bca73a7ff
    15/15:	https://codeload.github.com/laminas/laminas-validator/legacy.zip/93593684e70b8ed1e870cacd34ca32b0c0ace185
    Finished: success: 15, skipped: 0, failure: 0, total: 15
Package operations: 20 installs, 0 updates, 0 removals
  - Installing laminas/laminas-zendframework-bridge (1.0.4): Loading from cache
  - Installing laminas/laminas-component-installer (2.2.0): Loading from cache
  - Installing laminas/laminas-skeleton-installer (0.1.7): Loading from cache
  - Installing laminas/laminas-stdlib (3.2.1): Loading from cache
  - Installing laminas/laminas-loader (2.6.1): Loading from cache
  - Installing laminas/laminas-eventmanager (3.2.1): Loading from cache
  - Installing laminas/laminas-json (3.1.2): Loading from cache
  - Installing laminas/laminas-view (2.11.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing laminas/laminas-servicemanager (3.4.1): Loading from cache
  - Installing laminas/laminas-validator (2.13.4): Loading from cache
  - Installing laminas/laminas-escaper (2.6.1): Loading from cache
  - Installing laminas/laminas-uri (2.7.1): Loading from cache
  - Installing laminas/laminas-http (2.12.0): Loading from cache
  - Installing laminas/laminas-router (3.3.2): Loading from cache
  - Installing laminas/laminas-config (3.3.0): Loading from cache
  - Installing laminas/laminas-modulemanager (2.8.4): Loading from cache
  - Installing laminas/laminas-mvc (3.1.1): Loading from cache
  - Installing laminas/laminas-development-mode (3.2.1): Loading from cache
laminas/laminas-json suggests installing laminas/laminas-json-server (For implementing JSON-RPC servers)
laminas/laminas-json suggests installing laminas/laminas-xml2json (For converting XML documents to JSON)
laminas/laminas-view suggests installing laminas/laminas-authentication (Laminas\Authentication component)
laminas/laminas-view suggests installing laminas/laminas-feed (Laminas\Feed component)
laminas/laminas-view suggests installing laminas/laminas-filter (Laminas\Filter component)
laminas/laminas-view suggests installing laminas/laminas-i18n (Laminas\I18n component)
laminas/laminas-view suggests installing laminas/laminas-mvc-plugin-flashmessenger (laminas-mvc-plugin-flashmessenger component, if you want to use the FlashMessenger view helper with laminas-mvc versions 3 and up)
laminas/laminas-view suggests installing laminas/laminas-navigation (Laminas\Navigation component)
laminas/laminas-view suggests installing laminas/laminas-paginator (Laminas\Paginator component)
laminas/laminas-view suggests installing laminas/laminas-permissions-acl (Laminas\Permissions\Acl component)
laminas/laminas-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 1.* to handle lazy initialization of services)
laminas/laminas-validator suggests installing laminas/laminas-db (Laminas\Db component, required by the (No)RecordExists validator)
laminas/laminas-validator suggests installing laminas/laminas-filter (Laminas\Filter component, required by the Digits validator)
laminas/laminas-validator suggests installing laminas/laminas-i18n (Laminas\I18n component to allow translation of validation error messages)
laminas/laminas-validator suggests installing laminas/laminas-i18n-resources (Translations of validator messages)
laminas/laminas-validator suggests installing laminas/laminas-math (Laminas\Math component, required by the Csrf validator)
laminas/laminas-validator suggests installing laminas/laminas-session (Laminas\Session component, ^2.8; required by the Csrf validator)
laminas/laminas-validator suggests installing psr/http-message (psr/http-message, required when validating PSR-7 UploadedFileInterface instances via the Upload and UploadFile validators)
laminas/laminas-http suggests installing paragonie/certainty (For automated management of cacert.pem)
laminas/laminas-router suggests installing laminas/laminas-i18n (^2.7.4, if defining translatable HTTP path segments)
laminas/laminas-config suggests installing laminas/laminas-filter (^2.7.2; install if you want to use the Filter processor)
laminas/laminas-config suggests installing laminas/laminas-i18n (^2.7.4; install if you want to use the Translator processor)
laminas/laminas-modulemanager suggests installing laminas/laminas-console (Laminas\Console component)
laminas/laminas-mvc suggests installing http-interop/http-middleware (^0.4.1 to be used together with laminas-stratigility)
laminas/laminas-mvc suggests installing laminas/laminas-log (^2.9.1  To provide log functionality via LogFilterManager, LogFormatterManager, and LogProcessorManager)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-console (laminas-mvc-console provides the ability to expose laminas-mvc as a console application)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-i18n (laminas-mvc-i18n provides integration with laminas-i18n, including a translation bridge and translatable route segments)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-fileprg (To provide Post/Redirect/Get functionality around forms that container file uploads)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-flashmessenger (To provide flash messaging capabilities between requests)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-identity (To access the authenticated identity (per laminas-authentication) in controllers)
laminas/laminas-mvc suggests installing laminas/laminas-mvc-plugin-prg (To provide Post/Redirect/Get functionality within controllers)
laminas/laminas-mvc suggests installing laminas/laminas-paginator (^2.7 To provide pagination functionality via PaginatorPluginManager)
laminas/laminas-mvc suggests installing laminas/laminas-psr7bridge ((^0.2) To consume PSR-7 middleware within the MVC workflow)
laminas/laminas-mvc suggests installing laminas/laminas-servicemanager-di (laminas-servicemanager-di provides utilities for integrating laminas-di and laminas-servicemanager in your laminas-mvc application)
laminas/laminas-mvc suggests installing laminas/laminas-stratigility (laminas-stratigility is required to use middleware pipes in the MiddlewareListener)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Writing lock file
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

    Do you want a minimal install (no optional packages)? Y/n
Y
    Removing optional packages from composer.json
    Updating composer.json
infection/extension-installer: No extensions found
Removing laminas/laminas-skeleton-installer...
  - Removing laminas/laminas-skeleton-installer (0.1.7)
    Removed plugin laminas/laminas-skeleton-installer.
    Removing from composer.json
    Complete!
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? Y
> laminas-development-mode enable
You are now in development mode.
> php bin/update-gitignore.php
```

If you're on composer v2, you may need to use v1 stable:

```
composer self-update --stable 
```

**Comment by flipkickmedia** [comment]
$ composer -V
Composer 1.10.1 2020-03-13 20:34:27

$ php -v
PHP 7.3.21-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.21, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.21-1+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by flipkickmedia** [comment]
Your package downloads look very different to mine
 
I also tried a composer clear-cache and I get the same results.  This also happens on a Ubuntu20 box with php7.4 for me.

**Comment by flipkickmedia** [comment]
Could this be the source of the problem?  Apt installed versions?

apt search symfony | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

php-symfony-console/focal,now 4.3.8+dfsg-1ubuntu1 all [installed,automatic]
php-symfony-filesystem/focal,now 4.3.8+dfsg-1ubuntu1 all [installed,automatic]
php-symfony-finder/focal,now 4.3.8+dfsg-1ubuntu1 all [installed,automatic]
php-symfony-process/focal,now 4.3.8+dfsg-1ubuntu1 all [installed,automatic]
php-symfony-service-contracts/focal,now 1.1.8-1 all [installed,automatic]
