### ISSUE TITLE
Composer wraps up with Fatal Error

### ISSUE THREAD

**Issue by rbroen** [laminas/laminas-mvc-skeleton#32]
### Bug Report

|    Q        |   A
|------------ | ------
| laminas/laminas-mvc-skeleton  | fresh
| Ubuntu  | 20.10

#### Summary

Composer closes with a Fatal error and the Laminas installation questions are asked at every require action.

#### Current behavior

Composer closes with a Fatal error and the Laminas installation questions are asked at every require action.

#### How to reproduce

When running `composer create-project -s dev laminas/laminas-mvc-skeleton demo01` composer ends with the following error (but the additional packages questions were not asked):
```
Writing lock file
Generating autoload files
14 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /usr/share/php/Composer/IO/ConsoleIO.php on line 263 and defined in /usr/share/php/Symfony/Component/Console/Question/Question.php:38
Stack trace:
#0 /usr/share/php/Composer/IO/ConsoleIO.php(263): Symfony\Component\Console\Question\Question->__construct()
#1 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(151): Composer\IO\ConsoleIO->ask()
#2 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(83): Laminas\SkeletonInstaller\OptionalPackagesInstaller->requestMinimalInstall()
#3 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/Plugin.php(84): Laminas\SkeletonInstaller\OptionalPackagesInstaller->__invoke()
#4 [internal function]: Laminas\SkeletonInstaller\Plugin->installOptionalDependencies()
#5 /usr/share/php/Composer/EventDispatcher/Even in /usr/share/php/Symfony/Component/Console/Question/Question.php on line 38

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Question\Question::__construct() must be of the type string, array given, called in /usr/share/php/Composer/IO/ConsoleIO.php on line 263 and defined in /usr/share/php/Symfony/Component/Console/Question/Question.php:38
Stack trace:
#0 /usr/share/php/Composer/IO/ConsoleIO.php(263): Symfony\Component\Console\Question\Question->__construct()
#1 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(151): Composer\IO\ConsoleIO->ask()
#2 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(83): Laminas\SkeletonInstaller\OptionalPackagesInstaller->requestMinimalInstall()
#3 /home/robert/repos/demo01/vendor/laminas/laminas-skeleton-installer/src/Plugin.php(84): Laminas\SkeletonInstaller\OptionalPackagesInstaller->__invoke()
#4 [internal function]: Laminas\SkeletonInstaller\Plugin->installOptionalDependencies()
#5 /usr/share/php/Composer/EventDispatcher/Even in /usr/share/php/Symfony/Component/Console/Question/Question.php on line 38
```

The installation seems fine, bug the error will scare a lot of (new) users. And there is more...

When using the composer inside the docker container, the same errors appear after a composer require action (like: `composer require namshi/jose`), but first all extra package/module questions are asked and then the error occurs:
```
Updating root package
    Running an update to install optional packages

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Composer\Installer::setUpdate(), 0 passed in /var/www/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php on line 321 and exactly 1 expected in phar:///usr/local/bin/composer/src/Composer/Installer.php:1053
Stack trace:
#0 /var/www/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(321): Composer\Installer->setUpdate()
#1 /var/www/vendor/laminas/laminas-skeleton-installer/src/OptionalPackagesInstaller.php(107): Laminas\SkeletonInstaller\OptionalPackagesInstaller->runInstaller(Object(Composer\Package\RootPackage), Object(Laminas\SkeletonInstaller\Collection))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(84): Laminas\SkeletonInstaller\OptionalPackagesInstaller->__invoke()
#3 [internal function]: Laminas\SkeletonInstaller\Plugin_composer_tmp1->installOptionalDependencies(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispat in phar:///usr/local/bin/composer/src/Composer/Installer.php on line 1053
```

Every next require will result in the same actions/outcome.

#### Expected behavior

Fresh install of Laminas that gets new users into the mood of programming.

**Comment by froschdesign** [comment]
@rbroen 
What version of Composer and PHP are you using? (`composer --version` and `php -v`)

**Comment by rbroen** [comment]
On my Ubuntu 20.10 desktop (where the create-project was done):
```
(base) robert@robert-XPS-15-9570:~/repos/demo01$ composer --version
Composer 1.10.10 2020-08-03 11:35:19

(base) robert@robert-XPS-15-9570:~/repos/demo01$ php -v
PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```
In the docker container (as set up by the skeleton):
```
root@07ec6803c937:/var/www# composer --version          
Composer version 2.0.8 2020-12-03 17:20:38

root@07ec6803c937:/var/www# php -v
PHP 7.3.6 (cli) (built: May 31 2019 23:28:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by froschdesign** [comment]
> ```
> root@07ec6803c937:/var/www# composer --version          
> Composer version 2.0.8 2020-12-03 17:20:38
> ```

There is a problem with the installer and Composer with version 2.0. Related issue report: https://github.com/laminas/laminas-skeleton-installer/issues/13

**Comment by froschdesign** [comment]
> (base) robert@robert-XPS-15-9570:~/repos/demo01$ composer --version
> Composer 1.10.10 2020-08-03 11:35:19
> 
> (base) robert@robert-XPS-15-9570:~/repos/demo01$ php -v
> PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )

Unfortunately, I cannot reproduce the problem.

I tested an installation with optional packages with Composer version 1.10.19 and PHP version 7.4.9. And all this without error messages.

**Comment by rbroen** [comment]
This is very unfortunate... I can imagine other people using the same default Ubuntu 20.10 that I use. 
I bumped into this post that describes the same thing: https://stackoverflow.com/questions/65230097/problems-with-downloading-the-laminas-skeleton-application

I would really like to address this to ensure a good experience for new users.

**Comment by froschdesign** [comment]
@rbroen 
> I bumped into this post that describes the same thing: https://stackoverflow.com/questions/65230097/problems-with-downloading-the-laminas-skeleton-application

This problem on Slackoverflow is related to the issue report from above: https://github.com/laminas/laminas-skeleton-installer/issues/13  – based on the error message.
